### ISSUE TITLE
Classify roads as being within "built-up" or "undeveloped" areas

### ISSUE THREAD

**Issue by ctchervenkov** [matsim-eth/SCCER-Pipeline#20]
When monetizing externalities to compute the costs (e.g. air pollution costs), a distinction is made between roads lying in "built-up" and "undeveloped" areas. These are defined as follows (SN 641 828) :

Roads in built-up areas are roads with facilities within 50 m on both of their sides. If only a few empty sites exist on either side of the road, the area is still considered as built-up. Roads that have facilities only on one side are classified as 50/50 roads in built-up and undeveloped areas. Tunnels with ventilation installations should be taken into account as roads in undeveloped areas.

Therefore, we need to go through the links in the MATSim network, see how many facilities lie within this 50 m range on either side and then classify each link.

Open question : 
The standard states that if only a few empty sites exist on either side of the road, it is still built-up. What is "a few"? In other words, how many facilities does there need to be with 50 m of a road to be consider built-up?

**Comment by joemolloy** [comment]
will probably have to use osm land types, then map to osm ids, for the full/5050 definition.

[] Do this first for zurich, then extend to switzerland

**Comment by ctchervenkov** [comment]
Now according however to the Ecoplan / Infras methodology on which the updated ARE report is based, they basically compute population-weighted PM10 emissions. 
This suggests we would need to at least have the population density around each link in the network. However, we would need to define an area around each link for which we compute this density. Maybe a 1, 5 or 10 km radius around each link?
